### ISSUE TITLE
ReferenceError: System is not defined

### ISSUE THREAD

**Issue by jizusun** [MacKentoch/reactjs-facebook-tutorial-in-es6#1]
I got this error in my browser console, how can i fix this?

**Comment by MacKentoch** [comment]
It is `jspm` related but what version do you have?

_This kind of error can happen in some jspm versions (but should be fixed since a while)_

**I currently use  jspm version**

``` bash
jspm -v
```

> 0.16.34

I don't encounter this issue.

**Comment by jizusun** [comment]
Oh sorry,  I just **failed to** install jspm.

```
>> npm install && jspm install

npm WARN reactjs-facebook-tutorial-in-es6@1.0.0 No repository field.
jspm: command not found
```

I installed jspm **globally**, and it works.

This issue should be closed, , thanks for your help.

**Comment by MacKentoch** [comment]
It's ok 😄 

Glad to see it is resolved.
